name: rich_clipboard
description: Flutter plugin for accessing rich text and other data types in the system clipboard.
homepage: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard
repository: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter 
  rich_clipboard_android: 
      path: ../rich_clipboard_android 
  rich_clipboard_platform_interface:
      path: ../rich_clipboard_platform_interface 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
dependency_overrides:
  rich_clipboard_android:
    git:
      url: https://github.com/qi-shun-wang/rich_clipboard.git
      path: rich_clipboard_android 
  rich_clipboard_platform_interface:
    git:
      url: https://github.com/qi-shun-wang/rich_clipboard.git
      path: rich_clipboard_platform_interface 
flutter:
  plugin:
    platforms:
      android:
        default_package: rich_clipboard_android